# ใช้ Node.js รุ่นเบา
FROM node:18-alpine

# สร้าง working directory
WORKDIR /app

# คัดลอกไฟล์สำหรับติดตั้ง dependency
COPY package.json package-lock.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกไฟล์ทั้งหมดเข้า image
COPY . .

# สร้าง Prisma Client
RUN npx prisma generate

# คอมไพล์ TypeScript
RUN npm run build

# เปิดพอร์ต
EXPOSE 3001

# รันไฟล์ index.js ที่ build แล้ว
CMD ["node", "dist/index.js"]
